# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 104aba66433b1926fc0e85cc499317a5d53cae76f83635d40fd7b90a6cd79ebdd020a20e5bb13427fd0ec737fa95acfe2a5ff38f240d10ffac66a7f349a58b02

test:
  secret_key_base: 92fc39b95d4a3cfc98699e6199b7f39915fec7cc51bb134425b143849363dff6e63414553088bbe3e2797343d09f1062f35c875dd3febdb0e4c62a3103f5e25b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
